In [79]:
print("Hello Jupyter")

Hello Jupyter


In [80]:
import numpy as np

In [81]:
a=np.array([4,7,8])

In [82]:
a

array([4, 7, 8])

In [83]:
a.ndim

1

In [84]:
a=np.array([[7,9,3],[30,50,40]])
print(a)
print(a.ndim)

[[ 7  9  3]
 [30 50 40]]
2


In [85]:
a=np.array([[[9,8,3],[30,50,40],[99,54,34]]])
print(a)
print(a.ndim)

[[[ 9  8  3]
  [30 50 40]
  [99 54 34]]]
3


In [86]:
a.shape

(1, 3, 3)

In [87]:
a.size

9

In [88]:
a.itemsize

4

In [89]:
a=np.array([[1,2,3,4,5],[10,20,30,40,50],[6,7,8,4,3]],dtype="float64")
print(a)
print(a.ndim)

[[ 1.  2.  3.  4.  5.]
 [10. 20. 30. 40. 50.]
 [ 6.  7.  8.  4.  3.]]
2


In [90]:
a.shape


(3, 5)

In [91]:
a.size

15

In [92]:
a.itemsize

8

In [93]:
a[0,2]

3.0

In [94]:
a=np.array([[7,2,3,4,5],[10,20,60,40,50],[6,4,8,9,3]],dtype="int32")
print(a)
print(a.ndim)

[[ 7  2  3  4  5]
 [10 20 60 40 50]
 [ 6  4  8  9  3]]
2


In [95]:
a[0,2]

3

In [96]:
a[0,:]

array([7, 2, 3, 4, 5])

In [97]:
a[0,:3]

array([7, 2, 3])

In [98]:
a[:,2]

array([ 3, 60,  8])

In [99]:
a[:2,2:]

array([[ 3,  4,  5],
       [60, 40, 50]])

In [100]:
a[0,2]

3

In [101]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [102]:
x=np.ones((4,3))

In [103]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [104]:
x.dtype

dtype('float64')

In [105]:
x=np.ones((4,3),dtype="int64")

In [106]:
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [107]:
x.dtype

dtype('int64')

In [108]:
np.full((3,3),60)

array([[60, 60, 60],
       [60, 60, 60],
       [60, 60, 60]])

In [109]:
np.full_like(x,8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]], dtype=int64)

In [110]:
np.random.rand(4,4)

array([[0.53052774, 0.65147494, 0.1000846 , 0.63647569],
       [0.85210557, 0.47309009, 0.23612789, 0.08607802],
       [0.55556971, 0.29175331, 0.1496021 , 0.31178425],
       [0.10489618, 0.9324881 , 0.03233452, 0.31873965]])

In [111]:
np.random.randint(5,15,size=(4,4))

array([[ 9,  5, 10,  5],
       [ 5,  6,  5, 14],
       [ 5, 12,  6,  7],
       [12, 14, 11,  6]])

In [112]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [113]:
a=np.array([3,4,5,6,7])
b=np.array([20,30,40,50,60])

In [114]:
a+10

array([13, 14, 15, 16, 17])

In [115]:
a-10

array([-7, -6, -5, -4, -3])

In [116]:
a*2

array([ 6,  8, 10, 12, 14])

In [117]:
a/2

array([1.5, 2. , 2.5, 3. , 3.5])

In [118]:
a+b

array([23, 34, 45, 56, 67])

In [119]:
a**2

array([ 9, 16, 25, 36, 49], dtype=int32)

In [120]:
np.tan(a)

array([-0.14254654,  1.15782128, -3.38051501, -0.29100619,  0.87144798])

In [121]:
np.cos(b)

array([ 0.40808206,  0.15425145, -0.66693806,  0.96496603, -0.95241298])

In [122]:
np.matmul(a,b)

1100

In [123]:
n=np.arange(15)

In [124]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [125]:
n.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [126]:
n.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [127]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [128]:
np.arange(5,30,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [129]:
np.arange(20,6,-3)

array([20, 17, 14, 11,  8])

In [130]:
a=np.array([[4,5,7],[10,20,30]])


In [131]:
a.flatten()

array([ 4,  5,  7, 10, 20, 30])

In [132]:
a=np.array([1,2,3],dtype="float64")

In [133]:
np.reciprocal(a)

array([1.        , 0.5       , 0.33333333])

In [134]:
a=np.array([5,7,9])

In [135]:
b=np.array([2,4,13])

In [136]:
np.mod(a,b)

array([1, 3, 9], dtype=int32)

In [137]:
a=np.array([[1,2,3],[4,5,6]])

In [138]:
b=np.array([[5,6,7],[10,11,23]])

In [139]:
np.hstack([b,a])

array([[ 5,  6,  7,  1,  2,  3],
       [10, 11, 23,  4,  5,  6]])

In [140]:
np.vstack([b,a])

array([[ 5,  6,  7],
       [10, 11, 23],
       [ 1,  2,  3],
       [ 4,  5,  6]])